apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dkacza/git-ops-lab
    targetRevision: HEAD
    path: argo-cd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-tracker
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
